config/routes.rb
Rails.application.routes.draw do
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'
  get '/product/:id/', to: 'products#show', as: 'product'
  get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#delete'
  
  #resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to products_path
        else
            render.edit
        end
    end

    def delete
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end

    def show
        @product = Product.find(params[:id])
    end

    private
    def product_params 
        params.require(:product).permit(:name, :description, :price)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
<div>
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price %>
</div>
<div>
    <%= f.submit %>
</div>

<% end %>

app/views/products/index.html.erb
<h1>Lista de productos<h1>
    <%= link_to "Nuevo producto", products_new_path %>
 
<table>
    <tr>
        <thead>
        <th>Nombre</th>
        <th>Descripci{n</th>
        <th>Precio</th>
        </thead>
    </tr>
    <% @products.each do |product| %>
    <tr>
        <td><%= product.name%></td>
        <td><%= product.description%></td>
        <td><%= product.price%></td>
        <td>
            <!-- <%= link_to "Mostrar"%> -->
            <%= link_to "Editar", edit_product_path(product) %>
            <%= link_to "Eliminar", product, method: :delete, data: { confirm: "Deseas borrar el articulo?"} %>
        
        </td>
    </tr>
    <% end %>
    
</table>

app/views/products/new.html.erb
<%= form_for @product do |f| %>

<div>
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price %>
</div>
<div>
    <%= f.submit %>
</div>

<% end %>
  